language: node_js
node_js:
  - "stable"
install:
- npm install
- npm install coveralls 
script: "npm run test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
  email: false
